### DISCUSSION TITLE
Release v0.21.0

### DISCUSSION THREAD

**Discussion by TristonianJones** [google/cel-go#996] [Announcements]
## Features

Release v0.21.0 introduces extensions for `math` related operators as well as a host of other
minor improvements in conjunction with the new CEL Policy Compiler.

* [#923]
* [#931]
* [#933]
* [#955]
* [#959]
* [#930]
* [#919]
* [#932]
* [#978]

### CEL Policy Compiler

Policies which use CEL often evolve to express complex logic using multiple statements
and decision criteria. The CEL Policy Compiler provides an extensible format for parsing,
compiling, and composing expression graphs. Below is a simple example which can easily
be compiled to a single CEL expression.

```yaml
name: "my-policy"
rule:
  variables:
    - name: greeting
      expression: "'%s, %s!'"
    - name: people
      expression: >
       ['Tristan', 'Calla', 'Antoine', 'Jonathan', 'Sokwhan', 'Rebecca']
  match:
    - condition: "request.user in variables.people"
      output: "variables.greeting.format(['hello', request.user])"
    - output: "variables.greeting.format(['goodbye', 'stranger'])"
```

* [#924]
* [#961]
* [#977]
* [#989]
* [#991]

## Fixes

* [#934]
* [#935]
* [#936]
* [#958]
* [#962]
* [#987]
* [#960]
* [#988]
* [#981]

### Presence Test Semantics

The following two changes identified an issue where presence test was unexpectedly being performed over a scalar type and evaluating to `absent` rather than erroring. It is strongly advised to set the flag `cel.EnableErrorOnBadPresenceTest(true)` to avoid a logical correctness issue.

* [#922]
* [#939]

### Deprecation Cleanup

* [#921]

## New Contributors
* @testwill made their first contribution in https://github.com/google/cel-go/pull/911
* @patrickpichler made their first contribution in https://github.com/google/cel-go/pull/941
* @seirl made their first contribution in https://github.com/google/cel-go/pull/948
* @jduraniglesias made their first contribution in https://github.com/google/cel-go/pull/955
* @goccy made their first contribution in https://github.com/google/cel-go/pull/960

**Full Changelog**: https://github.com/google/cel-go/compare/v0.20.1...v0.21.0

<hr /><em>This discussion was created from the release <a href='https://github.com/google/cel-go/releases/tag/v0.21.0'>Release v0.21.0</a>.</em>
